# -*- coding: utf-8 -*-
"""Assignment-5byoutube.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1ftSG6G-5krL2Dfx0orm2iZNk94Im1Wqu

Youtube Downloader using library in Pypi
"""

#Assignment-5
#Day-5
#Date:02/07/2021
#Amal V.V
#amalvv2000cit@gmail.com

! pip install pytube

import pytube

url = 'https://www.youtube.com/watch?v=9t3gW1Djcgs'

youtube = pytube.YouTube(url)
video = youtube.streams.first()
video.download('../Video')