# -*- coding: utf-8 -*-
"""Day5Assignment-1 Prime.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1K5PEX3HVS5g2q_VjbLLSDZSCYa0YRSXo
"""

#Day-5
#Date:02/07/2021
#Amal V.V
#amalvv2000cit@gmail.com

"""**Prime Numbers or Not**"""

n = int(input("Enter a number: "))  
 
if n > 1:  
   for i in range(2,n):  
       if (n % i) == 0:  
           print("The entered number is not a prime number")  
           break  
   else:  
       print("The entered number is a prime number")         
else:  
   print("The entered number is not a prime number")